### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by dcrouch79** [thusoy/grunt-pylint#19]
Ubuntu 16.04
nodejs v7.4.0
npm v4.1.1
python v2.7.12
pip v9.0.1
Extract from npm-debug.log:

```
261 verbose stack Error: grunt-pylint@1.3.1 postinstall: `cd tasks/lib && pip install --no-index --no-deps --ignore-installed ./pylint-1.5.4.tar.gz ./astroid-1.4.4.tar.gz ./colorama-0.3.6.tar.gz ./six-1.$
261 verbose stack Exit status 2
261 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
261 verbose stack     at emitTwo (events.js:106:13)
261 verbose stack     at EventEmitter.emit (events.js:191:7)
261 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
261 verbose stack     at emitTwo (events.js:106:13)
261 verbose stack     at ChildProcess.emit (events.js:191:7)
261 verbose stack     at maybeClose (internal/child_process.js:885:16)
261 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
262 verbose pkgid grunt-pylint@1.3.1
263 verbose cwd /home/david/projects/cfg-acad
264 error Linux 4.4.0-59-generic
265 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
266 error node v7.4.0
267 error npm  v4.1.1
268 error code ELIFECYCLE
269 error grunt-pylint@1.3.1 postinstall: `cd tasks/lib && pip install --no-index --no-deps --ignore-installed ./pylint-1.5.4.tar.gz ./astroid-1.4.4.tar.gz ./colorama-0.3.6.tar.gz ./six-1.10.0.tar.gz ./l$
269 error Exit status 2
270 error Failed at the grunt-pylint@1.3.1 postinstall script 'cd tasks/lib && pip install --no-index --no-deps --ignore-installed ./pylint-1.5.4.tar.gz ./astroid-1.4.4.tar.gz ./colorama-0.3.6.tar.gz ./s$
270 error Make sure you have the latest version of node.js and npm installed.
270 error If you do, this is most likely a problem with the grunt-pylint package,
270 error not with npm itself.
270 error Tell the author that this fails on your system:
270 error     cd tasks/lib && pip install --no-index --no-deps --ignore-installed ./pylint-1.5.4.tar.gz ./astroid-1.4.4.tar.gz ./colorama-0.3.6.tar.gz ./six-1.10.0.tar.gz ./lazy-object-proxy-1.2.1.tar.gz$
270 error You can get information on how to open an issue for this project with:
270 error     npm bugs grunt-pylint
270 error Or if that isn't available, you can get their info via:
270 error     npm owner ls grunt-pylint
270 error There is likely additional logging output above.
271 verbose exit [ 1, true ]
```

**Comment by thusoy** [comment]
Hi, thanks for reporting this. I can reproduce this, but only if I don't have an executable pip on PATH. Can you confirm that you have an executable pip binary where you're executing this?

**Comment by thusoy** [comment]
And if you indeed do have pip on PATH, it would be very helpful if you could run
```bash
$ wget https://registry.npmjs.org/grunt-pylint/-/grunt-pylint-1.3.1.tgz
$ tar xf grunt-pylint-1.3.1.tgz
$ cd package/tasks/lib
$ pip install --no-index --no-deps --ignore-installed ./pylint-1.5.4.tar.gz ./astroid-1.4.4.tar.gz ./colorama-0.3.6.tar.gz ./six-1.10.0.tar.gz ./lazy-object-proxy-1.2.1.tar.gz ./wrapt-1.10.6.tar.gz --target .
```
manually, and see if that works, as that's basically what npm is doing. Paste any output here if doesn't work and I'll see what I can about it!

**Comment by ddarne** [comment]
I have the same issue. Posting the output after following your steps:
grunt-cli v1.2.0
grunt v0.4.5
npm 3.10.10
node v6.11.1
Python 2.7.13
pip 9.0.1

`$ pip install --no-index --no-deps --ignore-installed ./pylint-1.5.4.tar.gz ./astroid-1.4.4.tar.gz ./colorama-0.3.6.tar.gz ./six-1.10.0.tar.gz ./lazy-object-proxy-1.2.1.tar.gz ./wrapt-1.10.6.tar.gz --target .`

`Requirement './pylint-1.5.4.tar.gz' looks like a filename, but the file does not exist
Requirement './astroid-1.4.4.tar.gz' looks like a filename, but the file does not exist
Requirement './colorama-0.3.6.tar.gz' looks like a filename, but the file does not exist
Requirement './six-1.10.0.tar.gz' looks like a filename, but the file does not exist
Requirement './lazy-object-proxy-1.2.1.tar.gz' looks like a filename, but the file does not exist
Requirement './wrapt-1.10.6.tar.gz' looks like a filename, but the file does not exist
Processing ./pylint-1.5.4.tar.gz
\nException:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 602, in unpack_file
    tarfile.is_tarfile(filename) or
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2624, in is_tarfile
    t = open(name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1675, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/Users/user/dev/project/pylint-1.5.4.tar.gz'`

Any comments/suggestions appreciated!
